/// SQL query to create the USER table.
pub const CREATE_TABLE_USER: &str = r#"
CREATE TABLE USER (
 	id INT NOT NULL UNIQUE AUTO_INCREMENT,
 	username VARCHAR (127) NOT NULL UNIQUE,
 	password VARCHAR (127) NOT NULL, -- hashed + salt
 	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
 	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 	PRIMARY KEY (id)
);
"#;

/// SQL query to create the ACCOUNT table.
pub const CREATE_TABLE_ACCOUNT: &str = r#"
CREATE TABLE ACCOUNT (
 	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	account_number	VARCHAR (24) NOT NULL UNIQUE,
 	user_id INT NOT NULL UNIQUE,
	balance INT DEFAULT 0,
 	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
 	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 	PRIMARY KEY (id)
);
"#;

/// SQL query to create the TRANSACTION table.
pub const CREATE_TABLE_TRANSACTION: &str = r#"
CREATE TABLE TRANSACTION (
 	id INT NOT NULL UNIQUE AUTO_INCREMENT,
 	account_number VARCHAR (24) NOT NULL UNIQUE,
	seller VARCHAR (255) NOT NULL,
	amount DECIMAL,
 	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
 	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 	PRIMARY KEY (id)
);
"#;
